package.json, packages/cli/src/config/get/get-manager.ts, packages/cli/src/config/get/index.ts, packages/cli/src/s.ts, packages/cli/src/utils/check-version.ts, packages/entity/package.json, packages/error/package.json, packages/init/package.json, packages/platform/package.json, packages/specification/package.json, packages/utils/package.json
Add global compilation instructions
=> fix global build command

packages/cli/src/utils/logger.ts, packages/core/src/utils/logger.ts, packages/init/src/logger.ts, packages/platform/src/utils/logger.ts
修复： logger 输入了参数，但是输出日志出现 undefined 的问题
=> fix: logger message output undefined

.eslintrc.json, CONTRIBUTING.md, src/config/add/index.ts, src/config/common/common.ts, src/config/delete/index.ts, src/config/index.ts
Format the code in config dir with Prettier with VS code and add type defintion to them.
When I add the type definition, I find the [change](https://github.com/hanyang-sh/Serverless-Devs/commit/e28a44e1644d81722f300f192b71fff05e994aa6#diff-8087feb7ad35b2bfe4a98fba5ca8209cdc8d99b2618d141d936e0c4ef14fbd9bR18) would cause the errror as the eslint config of `no-unused-vars`, and I change it to 
```json
@typescript-eslint/no-unused-vars": [      2,      {        "args": "none"      }    ]
```
and you can refer to this [@typescript-eslint/no-unused-vars false positive in type declarations](https://stackoverflow.com/questions/63767199/typescript-eslint-no-unused-vars-false-positive-in-type-declarations)
=> refactor:ts types and format

package.json, src/cli/cli-manager.ts, src/cli/index.ts, src/core/command/command-manager.ts, src/core/component/index.ts, src/index.ts, src/utils/common.ts
=> fix access && yaml check

src/cli/index.ts, src/index.ts, src/utils/common.ts
=> fix template, access

src/config/get/index.ts, test/config/get.test.ts, test/utils/index.test.ts, test/utils/storage.test.ts
增加utils模块 中Index单测和storage单测功能
=> feat: add utils index and storage test

package.json, src/core/component/index.ts
=> fix access

src/cli/cli-manager.ts, src/config/add/index.ts, src/config/delete/index.ts, src/config/get/index.ts, src/config/index.ts, src/core/command/command-manager.ts, src/core/component/index.ts, src/index.ts, src/init/index.ts, src/init/init-config.ts, src/init/init-manager.ts, src/set/index.ts, src/specification/parse.ts, src/utils/command-util.ts, src/utils/common.ts
change os.platform()=='win32'?'' to emoji function
=> chore: add emoji function

src/init/init-config.ts
=> fix: init FFmpeg

components/readme.md
=> add fg cfc

docs/zh/command/clean.md, docs/zh/command/cli.md, docs/zh/command/component.md, docs/zh/command/init.md, docs/zh/command/readme.md, docs/zh/command/set.md, src/clean/index.ts, src/cli/index.ts, src/component/index.ts, src/config/delete/index.ts, src/config/get/index.ts, src/index.ts, src/init/index.ts, src/set/analysis/index.ts, src/set/locale/index.ts, src/set/registry/index.ts
- 更新代码中部分help message
- 更新docs文档
- 更新set registry的信息提醒
=> update help message

.github/workflows/npm-publish.yml, bin/s-set-workspace, package.json, shell/postbuild.sh, src/config/delete/index.ts, src/core/command/command-manager.ts, src/core/component/index.ts, src/error/index.ts, src/index.ts, src/set/index.ts, src/set/workspace/index.ts, src/utils/common.ts, src/utils/core.ts
https://github.com/Serverless-Devs/Serverless-Devs/discussions/269
=> Preview 2.0.93

docs/zh/yaml.md
=> docs: recommended s filename pattern

package.json
=> fix: 🐛 update new version (fix spinner)

docs/en/install.md, docs/en/quick_start.md
Translate Serverless-Devs/blob/master/docs/zh/install.md
=> Translate: Serverless-Devs/blob/master/docs/zh/install.md & quick_start.md

docs/en/default_provider_config/alibabacloud.md
docs：add English version default_provider_config/alibabacloud.md.
Most of the information comes from [AliCloud](https://www.alibabacloud.com).
=> docs：add English version default_provider_config/alibabacloud.md

package.json
fix: https://github.com/devsapp/fc/issues/603
=> ci: 🎡 version:2.0.99

.vscode/launch.json, package.json, src/cli/index.ts, src/component/index.ts, src/config/add/index.ts, src/config/get/index.ts, src/help/index.ts, src/index.ts, src/init/init-config.ts, src/init/init-manager.ts, src/special-commad/index.ts, src/utils/common.ts, test/special-command.test.ts
- 修复fc组件更改publish文件commands数据格式导致帮助显示错误的问题
- s -h
- s helloworld -h
- s cli fc -h
- s config add 兼容--aliasName参数
注意：
合并前请更改s的版本号和core的版本
=> pre 2.0.101

CONTRIBUTING.md
There is a NodeJS project but recommending contrubutors to use JUnit5 .
=> docs: replace JUnit5 with Jest in CONTRIBUTING.md

.vscode/launch.json, package.json, src/component/index.ts, src/init/init-config.ts
- 支持aliyun cli 的account接入
- 支持魔法变量this, config
- s init增加插件模板
- update minimist version
- no such file or directory, open 'xx.fc-info.zip'
- Windows 执行pre-deploy 失败
- s component --component devsapp/fc 命令不符合预期
=> pre 2.0.104

docs/en/yaml.md, docs/zh/yaml.md
**Bug detail**
```
please tell us …
```
=> docs: ✏️ 新增变量赋值文档

spec/zh/0.0.2/serverless_package_model/package_model.md
=> fix: example value for `Type` for plugin

docs/en/package_dev.md, spec/en/0.0.2/serverless_package_model/package_model.md, spec/zh/0.0.1/serverless_package_model/readme.md, spec/zh/0.0.2/serverless_package_model/package_model.md
=> fix: replace every 3.package_model.md with package_model.md

docs/en/quick_start.md, docs/readme_en.md, readme_en.md
fix typos in some English docs
=> fix: fix typo in docs

src/init/init-config.ts
**Bug detail**
update `s init` config for baidu and huawei serverless service
```
please tell us `PR url`，like: …
```
=> update s init config for baidu and huawei serverless service

CONTRIBUTORS.md
**Bug detail**
```
please tell us …
```
=> docs: add contributors

readme.md
Add OpenFunction component project link.
=> docs(README): add ofn project link

CONTRIBUTORS.md
Related PR https://github.com/awesome-fc/custom-container-docs/pull/14
=> Add contributor 

CONTRIBUTORS.md
=> Update contributor name

CONTRIBUTORS.md
```
Only a little bit is recommended. Rename key alias.
```
=> docs: CONTRIBUTORS.md

spec/zh/0.0.2/serverless_package_model/publish_model.md
- password => secret
- 随机后缀名${default-suffix}
=> Publish docs

spec/zh/0.0.2/serverless_package_model/publish_model.md
=> docs: ✏️ 自定义过滤器filter

spec/en/0.0.2/serverless_package_model/publish_model.md, spec/zh/0.0.2/serverless_package_model/publish_model.md
**Bug detail**
```
please tell us …
```
=> Add x-Kafka using MD

spec/en/0.0.2/serverless_package_model/publish_model.md, spec/zh/0.0.2/serverless_package_model/publish_model.md
**Bug detail**
```
please tell us …
```
=> update x-bucket doc

CNAME, LICENSE, docs/en/package_dev.md, docs/readme.md, docs/readme_en.md, docs/zh/package_dev.md, package.json, readme.md, readme_en.md, spec/en/0.0.2/readme.md, spec/readme.md, spec/readme_en.md, spec/zh/0.0.1/readme.md, spec/zh/0.0.2/readme.md
**Bug detail**
```
please tell us …
```
=> update docs & license

CONTRIBUTORS.md, src/init/init-config.ts
Signed-off-by: fanzhe328 <251327341@qq.com>
**Bug detail**
```
{
name: '[HTTP] Go1',
value: 'devsapp/start-fc-http-golang1.x',
isDeploy: true,
},
{
name: '[Event] Go1',
value: 'devsapp/start-fc-event-golang1.x', …
```
=> support go1 runtime init

docs/en/inner_env.md, docs/zh/inner_env.md
**Bug detail**
```
please tell us …
```
=> docs: ✏️ add Serverless Devs buildin env docs

docs/zh/readme.md
**Bug detail**
```
please tell us …
```
=> delete two world 工具

.github/workflows/npm-publish.yml, docs/en/command/component.md, docs/en/command/init.md, docs/en/command/readme.md, docs/zh/command/component.md, docs/zh/command/init.md, docs/zh/command/readme.md, package.json, src/cli/index.ts, src/component/index.ts, src/config/add/index.ts, src/config/delete/index.ts, src/config/get/index.ts, src/constant.ts, src/edit/index.ts, src/error/index.ts, src/help/index.ts, src/index.ts, src/init/index.ts, src/init/init-config.ts, src/init/init-manager.ts, src/set/proxy/index.ts, src/set/registry/index.ts, src/set/workspace/index.ts, src/special-commad/index.ts
- s 命令的输出是纯字符串
- s init python替换成3.9版本
- s init 模版时，针对有pattern属性的字段需要进行正则校验
- 魔法变量解析不符合预期
- s cli 异常时，退出code不符合预期
- s init 下载模版的时候，hook钩子函数报错，debug时需将错误日志显示出来
=> pre 2.1.10

docs/en/yaml.md, docs/zh/yaml.md, package.json, src/cli/index.ts, src/init/init-config.ts
- [s cli doesn't show subcommands](https://github.com/Serverless-Devs/Serverless-Devs/commit/0bd9b9170361dbf3eb419b866eeba4fe60ce64b8)
- [start-next-ssr=>start-next](https://github.com/Serverless-Devs/Serverless-Devs/commit/e8f7cd63167736cc96f2119bce345f18029cd09e)
- [puppeteer-nodejs => start-puppeteer](https://github.com/Serverless-Devs/Serverless-Devs/commit/5858408dcea9c27a1a17f9180c2592b001b4f30d)
- [actions支持通配符](https://github.com/Serverless-Devs/Serverless-Devs/commit/39225d3f0214af3468bdd5f2b619424c59c971b5)
=> Pre 2.1.12

docs/zh/install.md
> 修复45行错别字 "讲 s.exe" -> "将 s.exe"
> 顺便微调其它地方的语句与排版，使文档阅读起来更舒适
- X Update English documentation
首次参与开源，提交个小pr，如有不足之处感谢指出
=> docs: 优化排版，使文档更易于阅读与理解

package.json, src/init/index.ts, src/init/init-manager.ts, src/update-notifier/index.ts
-  s init support --uri
-  remove auto install in daemon
=> Release 2.1.15

__tests__/fixtures/verify/code/index.js, __tests__/fixtures/verify/config.yaml, __tests__/fixtures/verify/output.json, __tests__/fixtures/verify/readme.md, __tests__/fixtures/verify/s.yaml, __tests__/fixtures/verify/template.yaml, __tests__/fixtures/verify/verify.yaml, __tests__/verify.test.ts, package.json, src/command/verify/index.ts, src/utils/index.ts
**Bug detail**
> fix: `verify` command support `--output` parameter.
=> fix: `verify` command support `--output` parameter.

package.json, src/command/init/constant.ts
**Bug detail**
> fix: regular expression error on special tokens
=> fix: regular expression error on special tokens

docs/en/cicd.md, docs/en/command/clean.md, docs/en/command/cli.md, docs/en/command/component.md, docs/en/command/config.md, docs/en/command/custom.md, docs/en/command/env.md, docs/en/command/init.md, docs/en/command/preview.md, docs/en/command/registry.md, docs/en/command/set.md, docs/en/command/verify.md, docs/readme.md, docs/readme_en.md, docs/zh/command/custom.md, docs/zh/command/preview.md, docs/zh/command/registry.md, docs/zh/command/verify.md, docs/zh/development-manual/component.md, readme.md, readme_en.md
- Update `verify` doc.
- Fix issues in english docs.
=> docs: add `verify` doc

docs/en/command/readme.md, docs/en/quick_start.md, docs/zh/cicd.md, docs/zh/command/readme.md, docs/zh/quick_start.md
=> docs: edit yunxiao cicd

readme.md, readme_en.md
=> docs: upgrade node version

.github/workflows/pkg.yml, __tests__/fixtures/env/env.yaml, __tests__/fixtures/env/s.yaml, package.json, src/command/custom/index.ts, src/command/env/command/default/action.ts, src/utils/index.ts
- fix pkg.yaml
- remove 'project' in 'env.yaml'
=> feat: remove 'project' in env.yaml

docs/zh/development-manual/readme.md
-  Update Chinese documentation
=> doc: start-app markdown

docs/en/quick_start.md, docs/zh/quick_start.md, src/utils/index.ts
- fix: env not found when run env component
- docs: invalid taobao registry
=> fix: env not found when run env component

package.json
- feat: add flag at header in mock env
=> feat: add flag at header in mock env

package.json
=> fix load url component

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom-issue-template.md, .github/ISSUE_TEMPLATE/feature_request.md
=> feat: 🎸 add issue_template

docs/en/command/readme.md, docs/en/command/verify.md, docs/zh/command/readme.md, docs/zh/command/verify.md, docs/zh/development-manual/readme.md, package-lock.json, package.json, src/command/index.ts, src/command/registry/index.ts, src/command/verify/index.ts, src/utils/index.ts
- fix: registry schema incorrect
=> fix: registry schema incorrect

__tests__/error.test.ts, package-lock.json, package.json, src/command/custom/index.ts, src/utils/index.ts
- fix: print WARNING when use logger.tips
- fix: obfuscate [*]
=> fix: obfuscate [*]

src/index.ts
=> feat: add root warning

package-lock.json, package.json, src/command/config/command/get.ts
Give a better hint message for assess.yaml file permission issue.
=> fix: `s config get` access error message
